apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: edge-inferencing-events
  namespace: default
spec:
  replicas: 1
  service:
    type: NodePort
  rabbitmq:
    additionalPlugins:
      - rabbitmq_federation
      - rabbitmq_federation_management
      - rabbitmq_management
      - rabbitmq_prometheus
      - rabbitmq_stream
  persistence:
    storageClassName: default
---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: cv-system
  namespace: default
spec:
  tags:
  - administrator
  rabbitmqClusterReference:
    name: edge-inferencing-events
---
apiVersion: rabbitmq.com/v1beta1
kind: Vhost
metadata:
  name: edge-vhost
  namespace: default
spec:
  name: edge-vhost # vhost name
  rabbitmqClusterReference:
    name: edge-inferencing-events # rabbitmqCluster must exist in the same namespace as this resource
---
apiVersion: rabbitmq.com/v1beta1
kind: Exchange
metadata:
  name: cv-exchange
  namespace: default
spec:
  name: cv-exchange # name of the exchange
  type: direct # default to 'direct' if not provided; can be set to 'direct', 'fanout', 'headers', and 'topic'
  autoDelete: false
  durable: true
  vhost: edge-vhost # default to '/' if not provided
  rabbitmqClusterReference:
    name: edge-inferencing-events 
---
apiVersion: rabbitmq.com/v1beta1
kind: Binding
metadata:
  name: binding
  namespace: default
spec:
  vhost: "/edge-vhost" # default to '/' if not provided
  source: cv-exchange # an existing exchange
  destination: cv-txns # an existing queue or exchange
  destinationType: queue # can be 'queue' or 'exchange'
  routingKey: "inference-type"
  rabbitmqClusterReference:
    name: edge-inferencing-events # rabbitmqCluster must exist in the same namespace as this resource
---
apiVersion: rabbitmq.com/v1beta1
kind: Queue
metadata:
  name: cv-events
  namespace: default
spec:
  name: cv-events # name of the queue
  vhost: edge-vhost # default to '/' if not provided
  autoDelete: false
  durable: true # seting 'durable' to false means this queue won't survive a server restart
  rabbitmqClusterReference:
    name: edge-inferencing-events # rabbitmqCluster must exist in the same namespace as this resource
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: edge-permission
  namespace: default
spec:
  vhost: edge-vhost
  userReference:
    name: "cv-system"
  permissions:
    write: ".*"
    configure: ""
    read: ".*"
  rabbitmqClusterReference:
    name: edge-inferencing-events
